# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:6.11

    working_directory: ~/portfolio

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-{{ .Branch }}
            - yarn-packages-master
            - yarn-packages-

      - run: yarn install

      - save_cache:
          name: Save yarn cache
          paths:
            - node_modules
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}

      # run tests!
      - run: npm run test

      - run: npm run build

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git checkout gh-pages
              cp -r dist/* ./
              rm -rf dist
              #./deploy.sh
            fi
